# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atlascloud < Formula
  desc "CLI for AtlasCloud AI models"
  homepage "https://atlascloud.ai"
  version "0.1.9"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AtlasCloudAI/cli/releases/download/v0.1.9/cli_0.1.9_darwin_amd64.tar.gz"
      sha256 "d8a80371a9c9dcc23b69f7e7b08d5f353b636ad2d50fadd1f48fa932cb437772"

      define_method(:install) do
        bin.install "atlas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AtlasCloudAI/cli/releases/download/v0.1.9/cli_0.1.9_darwin_arm64.tar.gz"
      sha256 "862674ad818336e1d7317ddb52edfd297dc153546baeade84cc013c4f3cc4971"

      define_method(:install) do
        bin.install "atlas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AtlasCloudAI/cli/releases/download/v0.1.9/cli_0.1.9_linux_amd64.tar.gz"
      sha256 "cca021894ba92f21c4c21f92a70eb7bd84b332e669a3bc006c1701756a9c56a0"
      define_method(:install) do
        bin.install "atlas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AtlasCloudAI/cli/releases/download/v0.1.9/cli_0.1.9_linux_arm64.tar.gz"
      sha256 "8a3dd8c566a041fbfc14580b75561cbdb121bdf245ad25b00c818c5bc21fdf74"
      define_method(:install) do
        bin.install "atlas"
      end
    end
  end

  test do
    system "#{bin}/atlas", "version"
  end
end
