# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atlascloud < Formula
  desc "CLI for AtlasCloud AI models"
  homepage "https://atlascloud.ai"
  version "0.1.17"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AtlasCloudAI/cli/releases/download/v0.1.17/cli_0.1.17_darwin_amd64.tar.gz"
      sha256 "48ab6bde140419febe22035e973ac7bff2315528a0f8772458e852dcde4613b0"

      define_method(:install) do
        bin.install "atlas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AtlasCloudAI/cli/releases/download/v0.1.17/cli_0.1.17_darwin_arm64.tar.gz"
      sha256 "b83a5396b2241b8ddc34a473c1acbf233939ef1b6a4c01a318de0a69d79696ff"

      define_method(:install) do
        bin.install "atlas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AtlasCloudAI/cli/releases/download/v0.1.17/cli_0.1.17_linux_amd64.tar.gz"
      sha256 "b765fc3efba80df0f941296eecadd004164910ae4d354c24be3cdadbd9e57ec7"
      define_method(:install) do
        bin.install "atlas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AtlasCloudAI/cli/releases/download/v0.1.17/cli_0.1.17_linux_arm64.tar.gz"
      sha256 "d1109087a061654895cf1e5e576167025b4b67122415536a965eb3fff29853cf"
      define_method(:install) do
        bin.install "atlas"
      end
    end
  end

  test do
    system "#{bin}/atlas", "version"
  end
end
