# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Atlascloud < Formula
  desc "CLI for AtlasCloud AI models"
  homepage "https://atlascloud.ai"
  version "0.1.22"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/AtlasCloudAI/cli/releases/download/v0.1.22/cli_0.1.22_darwin_amd64.tar.gz"
      sha256 "41a45c4020d04dcedf9e7711afb3252de4f69c950261ba3c2db1b44d69fa5192"

      define_method(:install) do
        bin.install "atlas"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/AtlasCloudAI/cli/releases/download/v0.1.22/cli_0.1.22_darwin_arm64.tar.gz"
      sha256 "14ab7891926b303c598b39a985347b68f2626ebdcab0e77aef6f88436dd874a1"

      define_method(:install) do
        bin.install "atlas"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/AtlasCloudAI/cli/releases/download/v0.1.22/cli_0.1.22_linux_amd64.tar.gz"
      sha256 "4e81f6c4e23d1c4e7cc2b2c0c60fea4ac6528385b6023e8dfa091a8ba95ad959"
      define_method(:install) do
        bin.install "atlas"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/AtlasCloudAI/cli/releases/download/v0.1.22/cli_0.1.22_linux_arm64.tar.gz"
      sha256 "cf4a15bfe13242378cd1607751b6fe1c71b5fc2323b3a7f597d23181dc810557"
      define_method(:install) do
        bin.install "atlas"
      end
    end
  end

  test do
    system "#{bin}/atlas", "version"
  end
end
